import{a as P,S as E,i}from"./assets/vendor-Sa4a0LJu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const R="49355132-77de24cc11258b0936a6d4f49",$="https://pixabay.com/api/";async function h(t,r=1,a=15){try{const n=await P.get($,{params:{key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}});return{images:n.data.hits,total:n.data.totalHits}}catch(n){throw console.error("Error fetching images:",n),n}}const y=document.querySelector(".gallery"),s=document.querySelector(".loader");s||console.error("Error: '.loader' element not found!");let B=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(t=!1){s&&(t?s.classList.add("loader--under-button"):s.classList.remove("loader--under-button"),s.style.display="block")}function L(){s&&(s.style.display="none")}function M(){y.innerHTML=""}function w(t){if(!t||t.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const r=t.map(({webformatURL:a,largeImageURL:n,tags:e,likes:o,views:l,comments:v,downloads:q})=>{const f=e.split(", ").slice(0,3).join(", ");return`
        <li class="gallery-item">
          <a href="${n}" class="gallery-link" data-caption="${f}">
            <img src="${a}" alt="${f}" loading="lazy" class="gallery-image">
          </a>
          <div class="info">
            <p><b>Likes</b> ${o}</p>
            <p><b>Views</b> ${l}</p>
            <p><b>Comments</b> ${v}</p>
            <p><b>Downloads</b> ${q}</p>
          </div>
        </li>`}).join("");y.insertAdjacentHTML("beforeend",r),B.refresh()}const O=document.querySelector(".form"),p=document.querySelector("input[name='search-text']"),m=document.querySelector(".load-more");let c=1,u="";const d=15;let g=0;O.addEventListener("submit",async t=>{if(t.preventDefault(),u=p.value.trim(),c=1,!u){i.warning({message:"Please enter a search query!",position:"topRight"});return}M(),S(),b();try{const r=await h(u,c,d),a=r.images;if(g=r.total,!a.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}w(a),g>d&&x()}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),p.value=""}});m.addEventListener("click",async()=>{c+=1,b(!0);try{const r=(await h(u,c,d)).images;w(r),H(),c*d>=g&&(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),S())}catch{i.error({message:"Error loading more images.",position:"topRight"})}finally{L()}});function x(){m.hidden=!1}function S(){m.hidden=!0}function H(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
