import{a as g,S as m,i as c}from"./assets/vendor-Sa4a0LJu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const y="49355132-77de24cc11258b0936a6d4f49",h="https://pixabay.com/api/";async function b(n,o=1,t=20){try{return(await g.get(h,{params:{key:y,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:t}})).data.hits}catch(a){throw console.error("Error fetching images:",a),a}}const p=document.querySelector(".gallery"),s=document.querySelector(".loader");s||console.error("Error: '.loader' element not found!");let L=new m(".gallery a",{captionsData:"alt",captionDelay:250});function w(){s&&(s.style.display="inline-block")}function S(){s&&(s.style.display="none")}function q(){p.innerHTML=""}function P(n){if(!n||n.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const o=n.map(({webformatURL:t,largeImageURL:a,tags:e,likes:r,views:i,comments:f,downloads:d})=>{const l=e.split(", ").slice(0,3).join(", ");return`
        <li class="gallery-item">
          <a href="${a}" class="gallery-link" data-caption="${l}">
            <img src="${t}" alt="${l}" loading="lazy" class="gallery-image">
          </a>
          <div class="info">
            <p><b>Likes</b> ${r}</p>
            <p><b>Views</b> ${i}</p>
            <p><b>Comments</b> ${f}</p>
            <p><b>Downloads</b> ${d}</p>
          </div>
        </li>`}).join("");p.insertAdjacentHTML("beforeend",o),L.refresh()}const v=document.querySelector(".form"),u=document.querySelector("input[name='search-text']");v.addEventListener("submit",async n=>{n.preventDefault();const o=u.value.trim();if(!o){c.warning({message:"Please enter a search query!",position:"topRight"});return}q(),w();try{const t=await b(o);if(!t||t.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}P(t)}catch(t){c.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Fetch error:",t)}finally{S(),u.value=""}});
//# sourceMappingURL=index.js.map
